services:
  postgres:
    image: postgres:17-alpine
    container_name: psgr
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=task_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  fastapi:
    build: .
    image: fastapi
    container_name: fastapi
    env_file:
      - .env
    environment:
      - DB_HOST=psgr
      - DB_USER=postgres
      - DB_PASS=mypassword
      - DB_NAME=task_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:8.6.2-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

volumes:
  redis_data:
